test3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'final_test.views.home_page', name='home'),
    url(r'^add$', 'final_test.views.add_Q', name='add'),
    url(r'^answer/(\d+)/$', 'final_test.views.answer_page', name='answer'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^admin/', include(admin.site.urls)),
)

final_test/models.py
from django.db import models
from django.utils import timezone

class Quest(models.Model):
    question = models.TextField(default='')
    answer1 = models.TextField(default='')
    answer2 = models.TextField(default='')
    Nanswer1 = models.IntegerField(default=0)
    Nanswer2 = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now())

class Answer(models.Model):
    question = models.ForeignKey(Quest, default=None)
    select_ans = models.TextField(default='0')

final_test/views.py
from django.shortcuts import redirect,render
from final_test.models import Quest,Answer
from django.utils import timezone


def home_page(request):
    quest=Quest.objects.all()
    now = timezone.now()
    m3=[]
    m6=[]
    month=0
    if Quest.objects.count() != 0:
        for quests in quest:
            if now.month < quests.pub_date.month :
               month = 12+now.month
            if month - quests.pub_date.month <= 3 :
               m3.append(quests.id)
            if month - quests.pub_date.month <= 6 :
               m6.append(quests.id)
    return render(request, 'home.html',{'quest': quest,'count': Quest.objects.count(),'now':now ,'m3':m3,'m6':m6})

def add_Q(request):
    if request.method == 'POST':
        questions = request.POST.get('your_question')
        answers1 = request.POST.get('your_ans1')
        answers2 = request.POST.get('your_ans2')           
        Quest.objects.create(question=questions, answer1=answers1, answer2=answers2 ,Nanswer1=0,Nanswer2=0,pub_date =timezone.now())
        return redirect('/')
    return render(request, 'add.html')

def answer_page(request, quest_id):
    quest_ = Quest.objects.get(id=quest_id)
    answer_ = Answer.objects.filter(question=quest_)
    if (request.method == 'POST' and request.POST.get('send_ans', '') == 'send_ans'):
        Answer.objects.create(select_ans=request.POST.get('ans', "0") ,question=quest_)
        if(request.POST.get('ans', "0")=="1"):
           quest_.Nanswer1=int(quest_.Nanswer1)+1
           quest_.save()
        elif request.POST.get('ans', "0")=="2":
           quest_.Nanswer2=int(quest_.Nanswer2)+1
           quest_.save()
        return redirect('/answer/%d' % int(quest_id))
    return render(request, 'answer.html', {'quest_': quest_,'answer_':answer_})

final_test/templates/add.html
<html>
    <head>
        <title>Test3-5601012620064</title>
    </head>
    <body>
        <h1>ADD QUESTION</h1>
<form method="POST">
QUESTION :  <br>
<input name="your_question" id="id_question" placeholder="type your question" /> <br>
ANSWER : <br>
1)<input name="your_ans1" id="id_answer1" placeholder="type your answer1" /> <br>
2)<input name="your_ans2" id="id_answer2" placeholder="type your answer2" /> <br>
 <input type="submit" value="send question"        id="submit_Q"  >
            {% csrf_token %}
</form>
    </body>
</html>

final_test/templates/answer.html
<html>
    <head>
        <title>Test3-5601012620064</title>
    </head>
    <body>
        <h1>ANS MY QUESTION</h1>
<a href="/" id="back2home">[[back]]</a> </br>
<form method="POST">
QUESTION :  <br>
{{quest_.question}}<br>
ANSWER : <br>
<div class="answers">
    1)<input id="ans-2" type="radio" name="ans" value="1" />{{quest_.answer1}}<br>
    2)<input id="ans-1" type="radio" name="ans" value="2" />{{quest_.answer2}}<br>
</div>
 <input type="submit" value="send answer"        id="submit_A"  >
 <input type="hidden" value="send_ans"  name="send_ans">
            {% csrf_token %}
</form>
<br>
จำนวนผู้ตอบ<br>
{{quest_.answer1}} : {{quest_.Nanswer1}}<br>
{{quest_.answer2}} : {{quest_.Nanswer2}}<br>
    </body>
</html>

final_test/templates/home.html
<html>
    <head>
        <title>Test3-5601012620064</title>
    </head>
    <body>
        <h1>Test III</h1>
 <script type="text/javascript">
function changeNavigation(id) 
{document.getElementById('main').innerHTML=document.getElementById(id).innerHTML} 
</script>

Now : <u>{{now}}</u></br>
<a href="/add" name="addQ" id="add_Q">Add Question</a> </br>
เลือกการแบ่งช่วงเวลา---->
<FONT COLOR=green>
<span onClick="changeNavigation('alls')" name="all" >&nbsp;&nbsp;&nbsp;<u>[[ทั้งหมด]]</u>&nbsp;&nbsp;&nbsp;</span>
<span onClick="changeNavigation('years')" name="year" >&nbsp;&nbsp;&nbsp;<u>[[ปี{{now.year}}]]</u>&nbsp;&nbsp;&nbsp;</span>
<span onClick="changeNavigation('m3s')" name="m3" >&nbsp;&nbsp;&nbsp;<u>[[3เดือนก่อน]]</u>&nbsp;&nbsp;&nbsp;</span>
<span onClick="changeNavigation('m6s')" name="m6" >&nbsp;&nbsp;&nbsp;<u>[[6เดือนก่อน]]</u>&nbsp;&nbsp;&nbsp;</span>
</FONT>
</br>
</br>
</br>
<!--Main page-->
<td valign="center" ><dt>
<div class="test" id="main" align="center">
<p><FONT COLOR=red><u>ทั้งหมด</u></FONT></p>
{% if count != 0 %}
it's question<br>
{%endif%}
{% for quests in quest %}
<a href="/answer/{{ quests.id }}/" id="view_question_{{ quests.id }}"> {{quests.id}} {{quests.question}}</a> [[{{quests.pub_date}}]]
<br> 
{%endfor%}
</div>
</dt></td>


<!--all-->

<div id="alls" style="display: none">
<p><FONT COLOR=red><u>ทั้งหมด</u></FONT></p>
{% if count != 0 %}
it's question<br>
{%endif%}
{% for quests in quest %}
<a href="/answer/{{ quests.id }}/" id="view_question_{{ quests.id }}"> {{quests.id}} {{quests.question}}</a> [[{{quests.pub_date}}]]
<br> 
{%endfor%}
</div>


<!--ภายในปีเดียวกับปัจจุบัน-->
<div id="years" style="display: none">
<p><FONT COLOR=red><u>ปี{{now.year}}</u></FONT></p>
{% if count != 0 %}
it's question<br>
{%endif%}
{% for quests in quest %}
{% if now.year == quests.pub_date.year %}
<a href="/answer/{{ quests.id }}/" id="view_question_{{ quests.id }}"> {{quests.id}} {{quests.question}}</a> [[{{quests.pub_date}}]]
<br> 
{%endif%}
{%endfor%}
</div>

<!--ภายใน3เดือนก่อน-->
<div id="m3s" style="display: none">
<p><FONT COLOR=red><u>3เดือนก่อน </u></FONT></p>
{% if count != 0 %}
it's question<br>
{%endif%}
{% for idm3 in m3 %}
{% for quests in quest %}
{% if idm3 == quests.id %}
<a href="/answer/{{ quests.id }}/" id="view_question_{{ quests.id }}"> {{quests.id}} {{quests.question}}</a> [[{{quests.pub_date}}]]
<br> 
{%endif%}
{%endfor%}
{%endfor%}
</div>

<!--ภายใน6เดือนก่อน-->
<div id="m6s" style="display: none">
<p><FONT COLOR=red><u>6เดือนก่อน </u></FONT></p>
{% if count != 0 %}
it's question<br>
{%endif%}
{% for idm6 in m6 %}
{% for quests in quest %}
{% if idm6 == quests.id %}
<a href="/answer/{{ quests.id }}/" id="view_question_{{ quests.id }}"> {{quests.id}} {{quests.question}}</a> [[{{quests.pub_date}}]]
<br> 
{%endif%}
{%endfor%}
{%endfor%}
</div>
    </body>
</html>

test3/templates/home.html
<html>
    <head>
        <title>Test3-5601012620064</title>
    </head>
    <body>
        <h1>Test III</h1>
 
    </body>
</html>